config/routes.rb
Rails.application.routes.draw do
  get 'slam', to: 'slam#index'
  get '/gpt_chats', to: 'gpt_chats#index'
  get '/gpt_chats/search', to: 'gpt_chats#search', as: 'search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
require "openai"
require 'dotenv'
Dotenv.load

  before_action :set_common_variable

  private

  # APIキーを設定
  def set_common_variable
    @client = OpenAI::Client.new(api_key: ENV["YOUR_ENV_VARIABLE_FOR_API_KEY"])
  end


end

app/controllers/gpt_chats_controller.rb
require 'openai'

class GptChatsController < ApplicationController
  def index
  end

  # 入力したテキストに対して返答
  # def search
  #   @query = params[:query]
  #   response = @client.chat(
  #     parameters: {
  #         model: "gpt-3.5-turbo",
  #         messages: [{ role: "user", content: @query }],
  #     })

  #   @chats = response.dig("choices", 0, "message", "content")
  # end

  # 入力したテキストに対して返答
  def search
    @query = params[:query]

    response = @client.create_completion("gpt-3.5-turbo", {
      prompt: @query,
      max_tokens: 100
    })
  
    # 処理されたテキストを抽出
    @chats = response['choices'][0]['text'].strip
  end
  
end

app/controllers/slam_controller.rb
require 'nokogiri'
require 'httparty'
require 'cgi'

class SearchController < ApplicationController
  def index
    keyword = params[:keyword]
    return unless keyword
    final_keyword = "聖地巡礼 #{keyword}"
    search_term = CGI.escape(final_keyword)
    url = "https://www.google.com/search?q=#{search_term}&tbm=isch"

    response = HTTParty.get(url)
    parsed_page = Nokogiri::HTML(response.body)

    # Googleの画像検索結果から画像URLを取得（要素のCSSセレクタは適宜調整）
    image_elements = parsed_page.css('img')
    @image_urls = image_elements.map do |element|
      element.attr('src')
    end.slice(1..10)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gpt_chats_helper.rb
module GptChatsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/gpt_chats/index.html.erb
<div class="top">
  <h3>ChatGPTに聞きたいことを入力してください。</h3>
  <%= form_with(url: search_path, method: :get) do |form| %>
    <%= form.text_field :query, size: 50 %>
    <%= form.submit "検索" %>
  <% end %>
</div>

app/views/gpt_chats/search.html.erb
<div class="top">
  <h3>ChatGPTからの返信結果</h3>
  <br>
  <%= @chats %>
  <br>
  <h3>さらにChatGPTに聞いてみましょう。</h3>
  <%= form_with(url: search_path, method: :get) do |form| %>
    <%= form.text_field :query, size: 50 %>
    <%= form.submit "検索" %>
  <% end %>
  <br>
  <%= link_to 'TOPページ', search_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seiti</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="m-2 bg-light">
    <%= yield %>
  </body>
</html>

app/views/slam/index.html.erb
<div class="container my-5">
  <%= form_with url: search_path, method: :get, local: true, class: 'form-inline mb-3' do %>
    <div class="form-group mr-2">
      <%= label_tag :keyword, "検索キーワード", class: 'mr-2 text-primary' %>
      <%= text_field_tag :keyword, nil, class: 'form-control' %>
    </div>
    <%= submit_tag "検索", class: 'btn btn-primary' %>
  <% end %>

  <%= link_to "chatGPT", gpt_chats_path %>
  
  <p class="text-secondary">検索キーワード: <%= params[:keyword] %></p>

  <div class="bg-light rounded p-5">
    <div class="border bg-white p-1">
      <% if @image_urls %>
        <p class="font-weight-bold text-secondary">イメージ</p>
        <div class="row justify-content-center img-fluid rounded">
          <div class="col-auto">
            <% @image_urls.each do |url| %>
              <%= link_to url, target: "_blank", class:"col-6 col-md-3 mb-4" do %>
                <%= image_tag url, class: "fixed-size-image mb-3" %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% else %>
        <p class="font-weight-bold text-danger">該当する画像が見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>

<style>
  .fixed-size-image {
    width: 160px;
    height: 90px;
  }
</style>